### ISSUE TITLE
Improve pod health checks

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#623]
**Is your feature request related to a problem? Please describe.**
Standard pod health checks aren't great and lead to downtime when rolling out a deployment, when a pod is alive but not yet healthy

Consider using [django-healthchecks](https://github.com/mvantellingen/django-healthchecks) to provide more informative health for Kubernetes

**Comment by djjudas21** [comment]
Don't need anything fancy - just need to define `livenessProbe` and `readinessProbe`

**Comment by djjudas21** [comment]
Reopening because these have been partially backed out. Currently these probes are failing in preprod but I believe it's an issue with the server. Pod logs show the app starting up properly, but all the probes fail.

**Comment by djjudas21** [comment]
There's a problem with zeus specifically that means http probes (and `kubectl exec` and `kubectl logs`) don't work. I can't recreate it on other nodes, and a rebuild of zeus didn't help. There's an open issue with Microk8s for this: https://github.com/ubuntu/microk8s/issues/1770

Meanwhile there's a workaround for http probes in https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-728908503

```yml
  readinessProbe:
#    httpGet:
#      path: "/__META__/ready"
#      port: 3000
    exec:
      command:
        - "curl"
        - "--fail"
        - "http://localhost:3000/__META__/ready"
```
